services:
  - type: worker
    name: BatmanPump
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: PROXY_URL
        sync: false
